apiVersion : apps/v1
kind: Deployment
metadata:
  name: rayzengpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rayzengpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: rayzengpipelinesjavascriptdocker 
    spec:
      containers:
        - name: rayzengpipelinesjavascriptdocker 
          image: pipelinetestdeploy.azurecr.io/rayzengpipelinesjavascriptdocker
          ports:
          - containerPort: 8080